parameters:
  - name: tflocation
    type: string

  - name: appenv
    type: string


jobs:
  - job: Validate
    displayName: 'Validate'
    steps:
    - script: |
        pwd
        ls -l   
      name: Debugdir
      displayName: 'Running debug scripts'
      workingDirectory: '$(System.DefaultWorkingDirectory)'

    - task: CopyFiles@2
      displayName: 'Copying environment specific Terraform files'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/${{ parameters.tflocation }}/env-config/${{ parameters.appenv }}'
        Contents: '**'
        TargetFolder: '$(System.DefaultWorkingDirectory)/${{ parameters.tflocation }}'

    - task: TerraformInstaller@0
      displayName: install terraform
      inputs:
        terraformVersion: latest


    - task: TerraformCLI@0
      displayName: 'Terraform Init'
      env:
        TF_TOKEN_app_terraform_io: $(tfcloud-user-token)
      inputs:
        command: 'init'
        workingDirectory: $(System.DefaultWorkingDirectory)/${{ parameters.tflocation }}
        allowTelemetryCollection: true

    - task: TerraformCLI@0
      displayName: 'Terraform fmt'
      env:
        TF_TOKEN_app_terraform_io: $(tfcloud-user-token)
      inputs:
        command: 'fmt'
        commandOptions: "-check"
        workingDirectory: $(System.DefaultWorkingDirectory)/${{ parameters.tflocation }}
        allowTelemetryCollection: true
        
    - script: |
        
        ls -l
        
      name: Debug
      displayName: 'Running debug scripts'
      workingDirectory: ${{parameters.tflocation}}
